# Generated by Django 4.0.5 on 2022-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
