# Generated by Django 4.0.5 on 2022-06-12 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_site_date_posted_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
