# Generated by Django 4.0.5 on 2022-06-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_site_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='name',
            new_name='name_site',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=2000)),
                ('design', models.PositiveSmallIntegerField(choices=[(1, '1- Very Dissatisfied'), (2, '2- Dissatisfied'), (3, '3- bad'), (4, '4- OK'), (5, '5- neutral'), (6, '6- good'), (7, '7- very good'), (8, '8- Extremly good'), (9, '9- Perfect'), (10, '10 - Master Piece')], default=0)),
                ('usability', models.PositiveSmallIntegerField(choices=[(1, '1- Very Dissatisfied'), (2, '2- Dissatisfied'), (3, '3- bad'), (4, '4- OK'), (5, '5- neutral'), (6, '6- good'), (7, '7- very good'), (8, '8- Extremly good'), (9, '9- Perfect'), (10, '10 - Master Piece')], default=0)),
                ('content', models.PositiveSmallIntegerField(choices=[(1, '1- Very Dissatisfied'), (2, '2- Dissatisfied'), (3, '3- bad'), (4, '4- OK'), (5, '5- neutral'), (6, '6- good'), (7, '7- very good'), (8, '8- Extremly good'), (9, '9- Perfect'), (10, '10 - Master Piece')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
