# Generated by Django 4.0.5 on 2022-06-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_name_site_name_site_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='name_site',
            new_name='name',
        ),
    ]
