# Generated by Django 4.0.5 on 2022-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='reviews',
            field=models.ManyToManyField(null=True, to='api.review'),
        ),
    ]
