# Generated by Django 4.0.5 on 2022-06-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_review_content_alter_review_design_and_more'),
    ]

    operations = [
    ]



