# Generated by Django 4.0.5 on 2022-06-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220614_1901'),
    ]

    operations = [
    ]
